name: Get Branch Info
description: Sets up environment variables and generates setup names based on branch types and project names
inputs:
  branch_name:
    description: 'The name of the branch'
    required: true
  project_name:
    description: 'The name of the project'
    required: false
    default: 'noname'
  os:
    description: 'The operating system'
    required: false
    default: 'all'
outputs:
  pull_request:
    description: 'Indicates if it is a pull request'
  version:
    description: 'The version'
  release:
    description: 'Indicates if it is a release'
  feature:
    description: 'Indicates if it is a feature'
  tag:
    description: 'The tag'
  setup_name:
    description: 'The setup name'
runs:
  using: 'composite'
  steps:
    - name: Set up environment variables
      run: |
        branch_name="${{ inputs.branch_name }}"
        project_name="${{ inputs.project_name }}"
        os="${{ inputs.os }}"

        osa=""
        if [ "$os" != "all" ]; then
          osa="-$os"
        fi

        pullRequest=false
        version="stage"
        release=false
        feature=false

        if [ -n "$PROJECT_NAME" ] && [ "$project_name" == "noname" ]; then
          project_name="$PROJECT_NAME"
        fi

        if [ "$branch_name" == "integration" ]; then
          tag="pre-integration"
          version="99.999"
          setupBaseName="${project_name}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
          release=true
        elif [[ "$branch_name" =~ ^release/ ]]; then
          tag="${branch_name##*/}"
          IFS='.' read -r -a versionParts <<< "$tag"
          if [ ${#versionParts[@]} -eq 3 ]; then
            shortTag="${versionParts[0]}.${versionParts[1]}"
          fi
          version="${tag//.x/.999}"
          setupBaseName="${project_name}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
          release=true
        elif [[ "$branch_name" =~ ^feat(ure)?/ ]]; then
          version="${branch_name#*/}"
          version="${version//[-_]/ }"
          version="${version%% *}"
          tag="feat-$version"
          setupBaseName="feat-${project_name}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
          feature=true
        elif [[ "$branch_name" =~ ^PR.* ]]; then
          pullRequest=true
          setupBaseName="stage-${project_name}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
        fi

        echo "SETUP_BASE_NAME=$setupBaseName" >> $GITHUB_ENV
        echo "SETUP_NAME=$setupName" >> $GITHUB_ENV
        echo "PROJECT_NAME=$project_name" >> $GITHUB_ENV

        echo "pull_request=$pullRequest" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "release=$release" >> $GITHUB_OUTPUT
        echo "feature=$feature" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "setup_name=$setupName" >> $GITHUB_OUTPUT
      shell: bash