name: Get Branch Info
description: Sets up environment variables and generates setup names based on branch types and project names
inputs:
  branchName:
    description: 'The name of the branch'
    required: true
  projectName:
    description: 'The name of the project'
    required: false
    default: 'noname'
  os:
    description: 'The operating system'
    required: false
    default: 'all'
outputs:
  pullRequest:
    description: 'Indicates if it is a pull request'
  version:
    description: 'The version'
  release:
    description: 'Indicates if it is a release'
  feature:
    description: 'Indicates if it is a feature'
  tag:
    description: 'The tag'
  setupName:
    description: 'The setup name'
runs:
  using: 'composite'
  steps:
    - name: Set up environment variables
      run: |
        branchName="${{ inputs.branchName }}"
        projectName="${{ inputs.projectName }}"
        os="${{ inputs.os }}"

        osa=""
        if [ "$os" != "all" ]; then
          osa="-$os"
        fi

        pullRequest=false
        version="stage"
        release=false
        feature=false

        if [ -n "$PROJECT_NAME" ] && [ "$projectName" == "noname" ]; then
          projectName="$PROJECT_NAME"
        fi

        if [ "$branchName" == "integration" ]; then
          tag="pre-integration"
          version="99.999"
          setupBaseName="${projectName}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
          release=true
        elif [[ "$branchName" =~ ^release/ ]]; then
          tag="${branchName##*/}"
          IFS='.' read -r -a versionParts <<< "$tag"
          if [ ${#versionParts[@]} -eq 3 ]; then
            shortTag="${versionParts[0]}.${versionParts[1]}"
          fi
          version="${tag//.x/.999}"
          setupBaseName="${projectName}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
          release=true
        elif [[ "$branchName" =~ ^feat(ure)?/ ]]; then
          version="${branchName#*/}"
          version="${version//[-_]/ }"
          version="${version%% *}"
          tag="feat-$version"
          setupBaseName="feat-${projectName}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
          feature=true
        elif [[ "$branchName" =~ ^PR.* ]]; then
          pullRequest=true
          setupBaseName="stage-${projectName}-${version}"
          setupName="${setupBaseName}.${BUILD_ID}${osa}"
        fi

        echo "SETUP_BASE_NAME=$setupBaseName" >> $GITHUB_ENV
        echo "SETUP_NAME=$setupName" >> $GITHUB_ENV
        echo "PROJECT_NAME=$projectName" >> $GITHUB_ENV

        echo "pull_request=$pullRequest" >> $GITHUB_OUTPUT
        echo "version=$version" >> $GITHUB_OUTPUT
        echo "release=$release" >> $GITHUB_OUTPUT
        echo "feature=$feature" >> $GITHUB_OUTPUT
        echo "tag=$tag" >> $GITHUB_OUTPUT
        echo "setup_name=$setupName" >> $GITHUB_OUTPUT
      shell: bash