name: Run tests and publish report
on:
  workflow_call:
    inputs:
      status:
        type: string
        required: true
jobs:
  allure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Generate Allure Results for Reusable Workflows and Steps
        id: generate-results
        run: |
          mkdir -p allure-results
          if [ "${{ inputs.status }}" == "success" ]; then
            echo "<test-case status='passed'><name>Reusable Workflow 1</name></test-case>" > allure-results/reusable1.xml
          else
            echo "<test-case status='failed'><name>Reusable Workflow 1</name></test-case>" > allure-results/reusable1.xml
          fi
          if [ "${{ inputs.status }}" == "success" ]; then
            echo "<test-case status='passed'><name>Build with Gradle</name></test-case>" > allure-results/build.xml
          else
            echo "<test-case status='failed'><name>Build with Gradle</name></test-case>" > allure-results/build.xml
          fi

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ github.token }}
          publish_branch: gh-pages
          publish_dir: allure-history