name: Run tests and publish report
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 17

      - name: Generate Allure Results for Failed Steps
        if: failure()
        run: |
          mkdir -p allure-results
          echo "<test-case status='failed'><name>Build with Gradle</name></test-case>" > allure-results/test-case.xml
          echo "<test-case status='failed'><name>Run tests</name></test-case>" >> allure-results/test-case.xml

      - name: Load test report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: build/allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ github.token }}
          publish_branch: gh-pages
          publish_dir: allure-history