name: Test


on:
  push:
    branches-ignore:
      - '*'


#on:
#  push:
#    branches:
#      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST1: "test1"
      TEST2: "test2"

    steps:
    - name: Set up vars1
      run: |
        VAR1="Hello"
        echo "VAR1=${VAR1}" >> $GITHUB_ENV
        echo "joined=${{env.TEST1}}${{env.TEST2}}" >> $GITHUB_ENV

    - name: Set up vars2
      run: |
        echo "VAR2=${{env.VAR1}}" >> $GITHUB_ENV
          
    - name: Set up vars3
      run: |
        echo "VAR3=${{env.VAR2}}" >> $GITHUB_ENV
    
    - name: Set up vars4
      run: |
        echo "VAR4=${{env.VAR1}}_${{env.VAR2}}_${{env.VAR3}}" >> $GITHUB_ENV

    - name: Set up vars5
      run: |
        VAR_A="Hi"
        echo "VAR_A=${VAR_A}" >> $GITHUB_ENV

        VAR_B=${VAR_A}
        echo "VAR_B=${VAR_B}" >> $GITHUB_ENV

        VAR_C=${VAR_B}
        echo "VAR_C=${VAR_C}" >> $GITHUB_ENV

        echo "VAR_D=${VAR_A}_${VAR_B}_${VAR_C}" >> $GITHUB_ENV

    - name: Check files
      run: |
        echo "The value of 'VAR1' is ${{env.VAR1}}"
        echo "The value of 'VAR2' is ${{env.VAR2}}"
        echo "The value of 'VAR3' is ${{env.VAR3}}"
        echo "The value of 'VAR4' is ${{env.VAR4}}"

        echo "The value of 'VAR_A' is ${{env.VAR_A}}"
        echo "The value of 'VAR_B' is ${{env.VAR_B}}"
        echo "The value of 'VAR_C' is ${{env.VAR_C}}"
        echo "The value of 'VAR_D' is ${{env.VAR_D}}"

        echo "${{ env.joined }}"