name: version control
run-name: ${{ github.actor }} is checking the text server's version
on: [pull_request]
jobs:
  Version-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      
      - run: echo "💡 Pull request from branch ${{ github.head_ref }} to branch ${{ github.base_ref }}"
      
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      
      - name: check version
        run: |
          CHANGED_FILE=$(git diff --name-only "refs/remotes/origin/${{ github.base_ref }}"..."refs/remotes/origin/${{ github.head_ref }}" -- package.json)
          echo $CHANGED_FILE
          if [ -z "${CHANGED_FILE}" ] ; then
            echo "The file package.json has to be updated"
            exit 1
          else
            echo "The file package.json was updated"
          fi                    
      
      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Read and parse JSON file
        id: read_json
        run: |
          VERSION=$(jq -r '.version' package.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Use parsed VERSION
        run: echo "The value of 'version' is $VERSION"

      - run: echo "🍏 This job's status is ${{ job.status }}."