name: Test


#on:
#  push:
#    branches-ignore:
#      - '*'


on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      TEST1: "test1"
      TEST2: "test2"

    steps:
    - name: Set up vars
      run: |
        VAR1="Hello"
        echo "VAR1=${VAR1}" >> $GITHUB_ENV
        
        echo "VAR2=${{env.VAR1}}" >> $GITHUB_ENV

        VAR3=${{env.VAR2}}
        echo "VAR3=${VAR3}" >> $GITHUB_ENV

        echo "VAR4=${{env.VAR1}}_${{env.VAR2}}_${{env.VAR3}}" >> $GITHUB_ENV

        echo "joined=${{env.TEST1}}${{env.TEST2}}" >> $GITHUB_ENV
    
    - name: Check files
      run: |
        echo "The value of 'VAR1' is ${{env.VAR1}}"
        echo "The value of 'VAR2' is ${{env.VAR2}}"
        echo "The value of 'VAR3' is ${{env.VAR3}}"
        echo "The value of 'VAR4' is ${{env.VAR4}}"

        echo "${{ env.joined }}"